name: SARS-CoV-2-RBD_DMS_variants
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - altair=4.1
  - git-lfs
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - minimap2=2.18
  - natsort
  - nodejs
  - pbccs=6.0.0
  - pip
  - python=3.8
  - seaborn=0.11.1
  - snakemake=6.2.1
  - sra-tools=2.10.9
  - pip:
    - alignparse==0.2.4
    - dms-variants==0.8.9
